name: aws infra terraform deploy

on:
  workflow_dispatch:

jobs:
  aws-terraform-apply:
    runs-on: ubuntu-latest
    env:
      REGION: ap-southeast-1
    permissions:
      id-token: write
      contents: write
      pull-requests: write

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.REGION }}

      - name: Checkout Repository
        uses: actions/checkout@v4.1.2

      - name: "Setup terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.1

      - name: "Execute terraform plan for Dataflow"
        working-directory: ./terraform/environments/production
        run: |
          terraform init -backend-config "bucket=${{ secrets.TF_STATE_BUCKET }}"