name: aws infra terraform deploy

on:
  push:
    branch:
      - main
  workflow_dispatch:

jobs:
  aws-terraform-apply:
    runs-on: ubuntu-latest
    env:
      REGION: ap-southeast-1
    permissions:
      id-token: write
      contents: write
      pull-requests: write

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Checkout Repository
        uses: actions/checkout@v4.1.2

      - name: "Setup terraform"
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.1

      - name: "Terraform init backend config"
        working-directory: ./terraform
        run: |
          terraform init -backend-config "bucket=${{ secrets.TF_STATE_BUCKET }}"

      - name: "Terraform apply changes"
        working-directory: ./terraform
        run: |
          terraform apply -auto-approve